### ISSUE TITLE
Code Licence ?

### ISSUE THREAD

**Issue by fremag** [yk35/tinyply.net#5]
Hello,

What is the licence for this project ?
I could not find a nuget and I'd like to include some parts to read ply files in my ray tracer 

Thanks,
Fremag

**Comment by yk35** [comment]
@fremag 
The license of this software, like [tinyply](https://github.com/ddiakopoulos/tinyply), is public domain.
You can use  some parts of this source code.
I added LICENSE file.

**Comment by fremag** [comment]
Good news, thanks a lot.
